server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:80 # nacos服务地址
    gateway:
      routes:
        - id: user-service #路由标识，必须唯一
          uri: lb://userservice #路由目标地址
          predicates: #路由断言，判断路由是否符合规则
            - Path=/user/**
          filters:
            - AddRequestHeader=Truth,Sharon is a beauty
        - id: order-service #路由标识，必须唯一
          uri: lb://orderservice-abc #路由目标地址
          predicates: #路由断言，判断路由是否符合规则
            - Path=/order/**

